import type { Tool } from "@/types/content";

export const tools: Tool[] = [
  {
    slug: "digital-squishy-playground",
    name: "디지털 말랑이 놀이터",
    description:
      "브라우저에서 말랑한 젤을 누르고 늘리며 시각 효과와 합성 소리를 즐기는 무료 감각 놀이",
    category: "재미 도구",
    status: "available",
    icon: "●",
    href: "/tools/digital-squishy-playground",
    thumbnail: "/images/tools/thumbnails/digital-squishy-playground.svg",
    thumbnailAlt: "말랑한 젤을 누르고 늘리는 디지털 말랑이 놀이터 화면",
    tags: ["브라우저 즉시 실행", "모바일 가능", "감각 놀이"],
    popularity: 72,
    releasedAt: "2026-08-01",
    actionLabel: "놀러 가기",
    featuredOnHome: false,
  },
  {
    slug: "ai-prompt-generator",
    name: "AI 프롬프트 생성기",
    description:
      "아이디어와 필요한 기능을 입력하면 ChatGPT와 Codex에 바로 붙여넣을 수 있는 구조화된 프롬프트를 만들어주는 도구입니다.",
    category: "AI 도구",
    status: "available",
    icon: "✦",
    href: "/tools/ai-prompt-generator",
    thumbnail: "/images/tools/thumbnails/ai-prompt-generator.svg",
    thumbnailAlt: "입력 폼과 생성 결과가 함께 보이는 AI 프롬프트 생성기 화면",
    tags: ["AI 프롬프트 생성", "회원가입 없음", "바로 복사"],
    popularity: 98,
    releasedAt: "2026-07-18",
    popular: true,
    actionLabel: "도구 사용하기",
    featuredOnHome: true,
  },
  {
    slug: "sensory-toy-playground",
    name: "디지털 촉감 놀이터",
    description:
      "말랑이·슬랑이·크런치 말랑이·왁뿌볼을 누르고 늘리고 깨뜨려보는 무료 미니앱",
    category: "재미 도구",
    status: "available",
    icon: "◉",
    href: "/tools/sensory-toy-playground",
    thumbnail: "/images/tools/thumbnails/sensory-toy-playground.svg",
    thumbnailAlt: "슬라임과 왁뿌볼 등 여러 장난감을 고르는 디지털 촉감 놀이터 화면",
    tags: ["4가지 장난감", "모바일 가능", "소리 지원"],
    popularity: 78,
    releasedAt: "2026-07-29",
    actionLabel: "놀러 가기",
    featuredOnHome: false,
  },
  {
    slug: "pastel-stack-game",
    name: "파스텔 스택 쌓기",
    description:
      "블록을 타이밍에 맞춰 쌓고, 퍼펙트 콤보와 최고 높이에 도전하는 무료 미니게임",
    category: "재미 도구",
    status: "available",
    icon: "▰",
    href: "/tools/pastel-stack-game",
    thumbnail: "/images/tools/thumbnails/pastel-stack-game.svg",
    thumbnailAlt: "파스텔 블록이 높게 쌓인 스택 게임 플레이 화면",
    tags: ["타이밍 게임", "콤보 기록", "모바일 가능"],
    popularity: 84,
    releasedAt: "2026-07-30",
    popular: true,
    actionLabel: "게임 시작",
    featuredOnHome: false,
  },
  {
    slug: "pastel-color-sort",
    name: "파스텔 컬러 정렬 퍼즐",
    description:
      "섞여 있는 파스텔 색상을 같은 색끼리 모아 모든 용기를 정리하는 무료 퍼즐 게임",
    category: "퍼즐 게임",
    status: "available",
    icon: "◈",
    href: "/tools/pastel-color-sort",
    thumbnail: "/images/tools/thumbnails/pastel-color-sort.svg",
    thumbnailAlt: "투명 유리 용기에 파스텔 액체가 층별로 담긴 컬러 정렬 퍼즐 화면",
    tags: ["30개 레벨", "액체 정렬", "로컬 기록"],
    popularity: 94,
    releasedAt: "2026-08-02",
    popular: true,
    actionLabel: "게임 시작",
    featuredOnHome: false,
  },
  {
    slug: "pastel-memory-match",
    name: "파스텔 메모리 카드 맞추기",
    description:
      "카드를 뒤집어 같은 그림을 찾고 콤보와 최고 기록에 도전하는 무료 기억력 게임",
    category: "퍼즐 게임",
    status: "available",
    icon: "✦",
    href: "/tools/pastel-memory-match",
    thumbnail: "/images/tools/thumbnails/pastel-memory-match.svg",
    thumbnailAlt: "여러 파스텔 카드가 펼쳐진 메모리 카드 맞추기 화면",
    tags: ["기억력 게임", "콤보 점수", "모바일 가능"],
    popularity: 90,
    releasedAt: "2026-08-03",
    popular: true,
    actionLabel: "게임 시작",
    featuredOnHome: false,
  },
  {
    slug: "memory-token-battle",
    name: "메모리 토큰 배틀",
    description:
      "토큰의 위치를 기억해 짝을 찾고 2인 또는 로봇과 대결하는 무료 기억력 게임",
    category: "대전 게임",
    status: "available",
    icon: "✺",
    href: "/tools/memory-token-battle",
    thumbnail: "/images/tools/thumbnails/memory-token-battle.svg",
    thumbnailAlt: "색상 토큰 보드와 점수가 보이는 메모리 토큰 배틀 화면",
    tags: ["2인 대전", "로봇 대결", "기억력 게임"],
    popularity: 86,
    releasedAt: "2026-08-09",
    popular: true,
    actionLabel: "게임 시작",
    featuredOnHome: false,
  },
  {
    slug: "pastel-block-puzzle",
    name: "MAKEON 파스텔 블록 퍼즐",
    description:
      "파스텔 블록으로 줄을 완성하고 오늘·전체 온라인 랭킹에 도전하는 무료 블록 퍼즐 게임",
    category: "퍼즐 게임",
    status: "available",
    icon: "▦",
    href: "/tools/pastel-block-puzzle",
    thumbnail: "/images/tools/thumbnails/pastel-block-puzzle.svg",
    thumbnailAlt: "파스텔 블록과 다음 블록이 보이는 블록 퍼즐 플레이 화면",
    tags: ["온라인 랭킹", "모바일 조작", "블록 퍼즐"],
    popularity: 92,
    releasedAt: "2026-08-04",
    popular: true,
    actionLabel: "게임 시작",
    featuredOnHome: false,
  },
];
