begin;

create table if not exists public.game_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null check (char_length(nickname) between 2 and 12),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.game_scores (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  game_key text not null check (game_key in ('pastel_stack', 'pastel_color_sort', 'pastel_memory_match')),
  leaderboard_key text not null default 'overall',
  score integer not null check (score >= 0),
  level integer check (level is null or level >= 0),
  height integer check (height is null or height >= 0),
  moves integer check (moves is null or moves >= 0),
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  best_combo integer check (best_combo is null or best_combo >= 0),
  difficulty text,
  metadata jsonb not null default '{}'::jsonb,
  achieved_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint game_scores_user_game_scope_unique unique (user_id, game_key, leaderboard_key)
);

create table if not exists public.game_daily_scores (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  game_key text not null check (game_key in ('pastel_stack', 'pastel_color_sort', 'pastel_memory_match')),
  leaderboard_key text not null default 'overall',
  score_date date not null,
  score integer not null check (score >= 0),
  level integer check (level is null or level >= 0),
  height integer check (height is null or height >= 0),
  moves integer check (moves is null or moves >= 0),
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  best_combo integer check (best_combo is null or best_combo >= 0),
  difficulty text,
  metadata jsonb not null default '{}'::jsonb,
  achieved_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint game_daily_scores_user_game_scope_date_unique
    unique (user_id, game_key, leaderboard_key, score_date)
);

create table if not exists public.game_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  game_key text not null check (game_key in ('pastel_stack', 'pastel_color_sort', 'pastel_memory_match')),
  difficulty text,
  started_at timestamptz not null default now(),
  submitted_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.game_score_submissions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game_key text not null,
  game_session_id uuid not null references public.game_sessions(id) on delete cascade,
  submission_hash text not null,
  accepted boolean not null default false,
  created_at timestamptz not null default now(),
  constraint game_score_submissions_session_unique unique (game_session_id),
  constraint game_score_submissions_hash_unique unique (submission_hash)
);

create index if not exists game_scores_stack_rank_idx
  on public.game_scores (game_key, leaderboard_key, score desc, height desc, best_combo desc, achieved_at asc);
create index if not exists game_scores_level_rank_idx
  on public.game_scores (game_key, leaderboard_key, level desc, moves asc, duration_ms asc, achieved_at asc);
create index if not exists game_scores_difficulty_idx
  on public.game_scores (game_key, difficulty, score desc, duration_ms asc, moves asc);
create index if not exists game_daily_scores_rank_idx
  on public.game_daily_scores (score_date, game_key, leaderboard_key, score desc, height desc, best_combo desc, achieved_at asc);
create index if not exists game_sessions_user_game_idx
  on public.game_sessions (user_id, game_key, started_at desc);
create index if not exists game_submissions_rate_idx
  on public.game_score_submissions (user_id, game_key, created_at desc);

alter table public.game_profiles enable row level security;
alter table public.game_scores enable row level security;
alter table public.game_daily_scores enable row level security;
alter table public.game_sessions enable row level security;
alter table public.game_score_submissions enable row level security;

drop policy if exists "Users can read own game profile" on public.game_profiles;
create policy "Users can read own game profile"
  on public.game_profiles for select to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can create own game profile" on public.game_profiles;
create policy "Users can create own game profile"
  on public.game_profiles for insert to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update own game profile" on public.game_profiles;
create policy "Users can update own game profile"
  on public.game_profiles for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

revoke all on public.game_scores from anon, authenticated;
revoke all on public.game_daily_scores from anon, authenticated;
revoke all on public.game_sessions from anon, authenticated;
revoke all on public.game_score_submissions from anon, authenticated;
revoke all on public.game_profiles from anon, authenticated;

create or replace function public.is_better_stack_score(
  p_score integer,
  p_height integer,
  p_best_combo integer,
  p_duration_ms integer,
  c_score integer,
  c_height integer,
  c_best_combo integer,
  c_duration_ms integer
) returns boolean
language sql
immutable
set search_path = public
as $$
  select case
    when p_score <> c_score then p_score > c_score
    when p_height <> coalesce(c_height, 0) then p_height > coalesce(c_height, 0)
    when p_best_combo <> coalesce(c_best_combo, 0) then p_best_combo > coalesce(c_best_combo, 0)
    else p_duration_ms < coalesce(c_duration_ms, 2147483647)
  end;
$$;

create or replace function public.submit_stack_score(
  p_user_id uuid,
  p_game_session_id uuid,
  p_score integer,
  p_height integer,
  p_best_combo integer,
  p_duration_ms integer,
  p_difficulty text,
  p_submission_hash text,
  p_score_date date
) returns table (improved boolean, ignored boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session public.game_sessions%rowtype;
  v_current public.game_scores%rowtype;
  v_daily public.game_daily_scores%rowtype;
  v_improved boolean;
  v_daily_improved boolean;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text || ':pastel_stack', 0));

  if p_score_date <> (now() at time zone 'Asia/Seoul')::date then
    raise exception 'invalid_score_date';
  end if;

  select * into v_session
  from public.game_sessions
  where id = p_game_session_id and user_id = p_user_id
  for update;

  if not found or v_session.submitted_at is not null or v_session.game_key <> 'pastel_stack'
     or v_session.difficulty is distinct from p_difficulty then
    raise exception 'invalid_or_consumed_session';
  end if;

  if now() - v_session.started_at < interval '700 milliseconds'
     or now() - v_session.started_at > interval '6 hours' then
    raise exception 'invalid_session_duration';
  end if;

  if exists (
    select 1 from public.game_score_submissions
    where user_id = p_user_id and game_key = 'pastel_stack'
      and created_at > now() - interval '3 seconds'
  ) then
    raise exception 'rate_limit_short';
  end if;

  if (
    select count(*) from public.game_score_submissions
    where user_id = p_user_id and game_key = 'pastel_stack'
      and created_at > now() - interval '1 minute'
  ) >= 12 then
    raise exception 'rate_limit_minute';
  end if;

  select * into v_current from public.game_scores
  where user_id = p_user_id and game_key = 'pastel_stack' and leaderboard_key = 'overall'
  for update;

  if not found then
    v_improved := true;
  else
    v_improved := public.is_better_stack_score(
      p_score, p_height, p_best_combo, p_duration_ms,
      v_current.score, v_current.height, v_current.best_combo, v_current.duration_ms
    );
  end if;

  if v_improved then
    insert into public.game_scores (
      user_id, game_key, leaderboard_key, score, height, best_combo,
      duration_ms, difficulty, achieved_at, updated_at
    ) values (
      p_user_id, 'pastel_stack', 'overall', p_score, p_height, p_best_combo,
      p_duration_ms, p_difficulty, now(), now()
    )
    on conflict (user_id, game_key, leaderboard_key) do update set
      score = excluded.score,
      height = excluded.height,
      best_combo = excluded.best_combo,
      duration_ms = excluded.duration_ms,
      difficulty = excluded.difficulty,
      achieved_at = excluded.achieved_at,
      updated_at = excluded.updated_at;
  end if;

  select * into v_daily from public.game_daily_scores
  where user_id = p_user_id and game_key = 'pastel_stack'
    and leaderboard_key = 'overall' and score_date = p_score_date
  for update;

  if not found then
    v_daily_improved := true;
  else
    v_daily_improved := public.is_better_stack_score(
      p_score, p_height, p_best_combo, p_duration_ms,
      v_daily.score, v_daily.height, v_daily.best_combo, v_daily.duration_ms
    );
  end if;

  if v_daily_improved then
    insert into public.game_daily_scores (
      user_id, game_key, leaderboard_key, score_date, score, height,
      best_combo, duration_ms, difficulty, achieved_at, updated_at
    ) values (
      p_user_id, 'pastel_stack', 'overall', p_score_date, p_score, p_height,
      p_best_combo, p_duration_ms, p_difficulty, now(), now()
    )
    on conflict (user_id, game_key, leaderboard_key, score_date) do update set
      score = excluded.score,
      height = excluded.height,
      best_combo = excluded.best_combo,
      duration_ms = excluded.duration_ms,
      difficulty = excluded.difficulty,
      achieved_at = excluded.achieved_at,
      updated_at = excluded.updated_at;
  end if;

  update public.game_sessions set submitted_at = now() where id = p_game_session_id;
  insert into public.game_score_submissions (
    user_id, game_key, game_session_id, submission_hash, accepted
  ) values (
    p_user_id, 'pastel_stack', p_game_session_id, p_submission_hash, v_improved
  );

  return query select v_improved, not v_improved;
end;
$$;

create or replace function public.get_stack_rankings(
  p_period text,
  p_user_id uuid,
  p_limit integer default 20
) returns table (
  rank bigint,
  nickname text,
  score integer,
  level integer,
  height integer,
  moves integer,
  duration_ms integer,
  best_combo integer,
  difficulty text,
  achieved_at timestamptz,
  is_current_user boolean
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if p_period = 'today' then
    return query
      with ranked as (
        select row_number() over (
          order by s.score desc, s.height desc, s.best_combo desc, s.achieved_at asc
        ) as position, p.nickname, s.user_id, s.score, s.level, s.height, s.moves,
          s.duration_ms, s.best_combo, s.difficulty, s.achieved_at
        from public.game_daily_scores s
        join public.game_profiles p on p.user_id = s.user_id
        where s.game_key = 'pastel_stack' and s.leaderboard_key = 'overall'
          and s.score_date = (now() at time zone 'Asia/Seoul')::date
      )
      select r.position, r.nickname, r.score, r.level, r.height, r.moves,
        r.duration_ms, r.best_combo, r.difficulty, r.achieved_at,
        r.user_id = p_user_id
      from ranked r
      where r.position <= greatest(1, least(p_limit, 20)) or r.user_id = p_user_id
      order by r.position;
  elsif p_period = 'all' then
    return query
      with ranked as (
        select row_number() over (
          order by s.score desc, s.height desc, s.best_combo desc, s.achieved_at asc
        ) as position, p.nickname, s.user_id, s.score, s.level, s.height, s.moves,
          s.duration_ms, s.best_combo, s.difficulty, s.achieved_at
        from public.game_scores s
        join public.game_profiles p on p.user_id = s.user_id
        where s.game_key = 'pastel_stack' and s.leaderboard_key = 'overall'
      )
      select r.position, r.nickname, r.score, r.level, r.height, r.moves,
        r.duration_ms, r.best_combo, r.difficulty, r.achieved_at,
        r.user_id = p_user_id
      from ranked r
      where r.position <= greatest(1, least(p_limit, 20)) or r.user_id = p_user_id
      order by r.position;
  else
    raise exception 'invalid_ranking_period';
  end if;
end;
$$;

revoke all on function public.is_better_stack_score(integer, integer, integer, integer, integer, integer, integer, integer) from public, anon, authenticated;
revoke all on function public.submit_stack_score(uuid, uuid, integer, integer, integer, integer, text, text, date) from public, anon, authenticated;
revoke all on function public.get_stack_rankings(text, uuid, integer) from public, anon, authenticated;
grant execute on function public.submit_stack_score(uuid, uuid, integer, integer, integer, integer, text, text, date) to service_role;
grant execute on function public.get_stack_rankings(text, uuid, integer) to service_role;

commit;
